# Generated by Django 5.2 on 2025-08-30 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_news_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('source_url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('processed', 'Processed'), ('failed', 'Failed')], default='raw', max_length=20)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_news', to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('news_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newstype')),
                ('raw_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_versions', to='news.rawnews')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedNewsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('tagged_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.taggednews')),
            ],
            options={
                'db_table': 'tagged_news_categories',
                'unique_together': {('tagged_news', 'category')},
            },
        ),
        migrations.AddField(
            model_name='taggednews',
            name='categories',
            field=models.ManyToManyField(related_name='tagged_news', through='news.TaggedNewsCategories', to='category.category'),
        ),
        migrations.CreateModel(
            name='TaggedNewsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.tag')),
                ('tagged_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.taggednews')),
            ],
            options={
                'db_table': 'tagged_news_tags',
                'unique_together': {('tagged_news', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='taggednews',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_news', through='news.TaggedNewsTags', to='category.tag'),
        ),
    ]
