# Generated by Django 5.2 on 2025-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggednews',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
