# Generated by Django 5.2 on 2025-09-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_taggednews_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnews',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
